from pygame import RESIZABLE

#
# Display
MAP_DEFAULT_POS = [0, 0]

START_GRID_DENSITY = 10
MIN_GRID_DENSITY = 5
MAX_GRID_DENSITY = 100

DISPLAY_WIDTH = START_GRID_DENSITY * 100 + 1
DISPLAY_HEIGHT = START_GRID_DENSITY * 70 + 1
DISPLAY_FLAGS = RESIZABLE

FPS_MAX = 60
#
# Colors
COLOR_SKY_BLUE = (135, 206, 250)
COLOR_BLACK = (0, 0, 0)

#
# Layers

LAYER_BACKGROUND = 1
