from pygame import RESIZABLE


MAP_DEFAULT_POSITION = [0, 0]

GRID_MIN_DENSITY = 5
GRID_START_DENSITY = 8
GRID_MAX_DENSITY = 100

DISPLAY_MAX_FPS = 60

DISPLAY_WIDTH = GRID_START_DENSITY * 100 + 1
DISPLAY_HEIGHT = GRID_START_DENSITY * 70 + 1
DISPLAY_FLAGS = RESIZABLE
