from pygame import RESIZABLE


MAP_DEFAULT_POSITION = [0, 0]

GRID_MIN_DENSITY = 5
GRID_START_DENSITY = 10
GRID_MAX_DENSITY = 100

DISPLAY_MAX_FPS = 60

COLOR_SKY_BLUE = (135, 206, 250)
COLOR_BLACK = (0, 0, 0)

DISPLAY_WIDTH = GRID_START_DENSITY * 100 + 1
DISPLAY_HEIGHT = GRID_START_DENSITY * 70 + 1
DISPLAY_FLAGS = RESIZABLE

# Constants for Sprites `_layer` attribute.
LAYER_BACKGROUND = 1
LAYER_ROADS = 2


LAYER_UI = 100
